services:
  oracle-db:
    image: gvenzl/oracle-free:latest
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=autoflex
      - APP_USER=autoflex
      - APP_USER_PASSWORD=autoflex
    volumes:
      - oracle_data:/opt/oracle/oradata

volumes:
  oracle_data: